unknown:
  - f
equations:
  left:
    - f = sin(2 * 3.14 * y)
  top:
    - f = 0
  bottom:
    - f = 0
  domain:
    - grad(f, x) + 0.5 * f * grad(f, y) - 0.25 * (0.01 / 3.14) * grad(grad(f, y), y) = 0