unknown:
  - f
residuals:
  top:
    - f
  bottom:
    - f
  left:
    - f
  right:
    - f
  domain:
    - "grad(grad(f, x), x) + grad(grad(f, y), y) + (2 * (8 * 3.14) ** 2 - 1) * sin(8 * 3.14 * x) * sin(8 * 3.14 * y)"