unknown:
  - f
equations:
  top:
    - f = 0
  bottom:
    - f = 0
  left:
    - f = 0
  right:
    - f = 0
  domain:
    - grad(grad(f, x), x) + grad(grad(f, y), y) = - (2 * (8 * 3.14) ** 2 - 1) * sin(8 * 3.14 * x) * sin(8 * 3.14 * y)