unknown:
  - u
  - v
  - p
residuals:
  top:
    - u
    - v - 1
  bottom:
    - u
    - v
  left:
    - u
    - v
  right:
    - u
    - v
  domain:
    - u * grad(u, x) + v * grad(u, y) + grad(p, x) - 1/100 * (grad(grad(u, x), x) + grad(grad(u, y), y))
    - u * grad(v, x) + v * grad(v, y) + grad(p, y) - 1/100 * (grad(grad(v, x), x) + grad(grad(v, y), y))
    - grad(u, x) + grad(v, y)